<?php

declare(strict_types=1);

namespace App\Services;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\URL;

/**
 * Per-page SEO i18n metadata — reciprocal hreflang alternates, x-default,
 * and a self-referencing canonical (docs/06-seo-architecture.md §5).
 *
 * Every locale lives under a /{locale}/ prefix (see routes/web/public.php +
 * SetLocale). Alternates are generated by temporarily pointing URL::defaults
 * at each locale, then restoring the request's own locale so nothing
 * downstream sees a stale prefix.
 */
class SeoService
{
    /**
     * @return array<string, string> locale (+ 'x-default') => absolute URL
     */
    public function hreflangAlternatesForRequest(Request $request): array
    {
        $route = $request->route();
        $name = $route?->getName();

        if ($name === null) {
            return [];
        }

        $supported = config('clinicest.locales.supported', ['en']);
        $default = config('clinicest.locales.default', 'en');
        $current = app()->getLocale();

        $params = $route->parameters();
        unset($params['locale']);

        $alternates = [];

        foreach ($supported as $locale) {
            URL::defaults(['locale' => $locale]);
            $alternates[$locale] = route($name, $params);
        }

        // Restore the ambient locale for the rest of the request.
        URL::defaults(['locale' => $current]);

        if (count($supported) > 1) {
            $alternates['x-default'] = $alternates[$default] ?? reset($alternates);
        }

        return $alternates;
    }

    /**
     * Self-referencing canonical = the current page's URL in the active
     * locale, without query string.
     */
    public function canonicalForRequest(Request $request): string
    {
        return $request->url();
    }

    public function defaultTitle(string $pageTitle): string
    {
        return "{$pageTitle} | ".config('app.name');
    }
}
